import { Listing } from "@/lib/types";

export const OFFICIAL_USER_ID = "official";

export const SEED_LISTINGS: Listing[] = [
  {
    id: "fender-stratocaster-american-pro-ii",
    title: "Fender Stratocaster American Pro II",
    description: "Sunburst finish, maple neck. Played a handful of gigs, no dings or scratches. Includes hardshell case and strap.",
    category: "Guitars",
    condition: "Like New",
    price: 145000,
    location: "Bangalore",
    imageUrl: "https://images.pexels.com/photos/12976809/pexels-photo-12976809.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-01T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "yamaha-trbx304-bass-guitar",
    title: "Yamaha TRBX304 Bass Guitar",
    description: "4-string bass in Translucent Black. Punchy MFD pickups, great for funk and jazz. Comes with padded gig bag.",
    category: "Bass",
    condition: "Good",
    price: 38000,
    location: "Mumbai",
    imageUrl: "https://yamahamusicstore.in/products-images/enlarge-image/ZG35320.jpg",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-02T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "roland-td-17kvx-electronic-drum-kit",
    title: "Roland TD-17KVX Electronic Drum Kit",
    description: "Mesh heads on all drums, Bluetooth module for play-along. Practically new, used in a home studio only. Stool and sticks included.",
    category: "Drums",
    condition: "New",
    price: 82000,
    location: "Delhi",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/HK_TKO_%E5%B0%87%E8%BB%8D%E6%BE%B3_Tseung_Kwan_O_%E5%BA%B7%E5%9F%8E_LOHAS_Park_shopping_mall_shop_%E6%9F%8F%E6%96%AF%E7%90%B4%E8%A1%8C_Parsons_Music_November_2021_SS2_17.jpg",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-03T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "korg-minilogue-xd-polyphonic-synthesizer",
    title: "Korg Minilogue XD Polyphonic Synthesizer",
    description: "16-voice analog polysynth with digital multi-engine. Deep modulation matrix and a gorgeous sequencer. Mint condition.",
    category: "Keyboards",
    condition: "Like New",
    price: 55000,
    location: "Bangalore",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRGSxe8UVwCzz5CJwQnvBgWjSgkJYx5WPDd0L2ys7U9ZXZjDvrNfM86eE&s=10",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-04T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "marshall-dsl40cr-tube-combo-amp",
    title: "Marshall DSL40CR Tube Combo Amp",
    description: "40-watt all-valve combo with reverb. Classic British crunch on channel 1, smooth leads on channel 2. Has a small scuff on the tolex but sounds phenomenal.",
    category: "Amplifiers",
    condition: "Fair",
    price: 32000,
    location: "Mumbai",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5gXeFJv0mP4ZMsuCgC4y5JRdF_CnNj1vgwJ6DIn81MyWbVKMIQurNNfE2&s=10",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-05T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "boss-re-20-space-echo-delay-pedal",
    title: "Boss RE-20 Space Echo Delay Pedal",
    description: "Twin pedal recreating the legendary Roland RE-201 tape echo. 12 modes, stereo output. Perfect for ambient and dub textures.",
    category: "Effects & Pedals",
    condition: "Good",
    price: 14500,
    location: "Delhi",
    imageUrl: "https://images.pexels.com/photos/4088803/pexels-photo-4088803.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-06T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "pioneer-ddj-400-dj-controller",
    title: "Pioneer DDJ-400 DJ Controller",
    description: "2-channel Rekordbox controller. Jog wheels feel great, built-in sound card, performance pads. Used for about 6 months.",
    category: "DJ Equipment",
    condition: "Good",
    price: 28000,
    location: "Bangalore",
    imageUrl: "https://files.vplak.com/500-images/pioneer/DDJ-REV5/black/image-1.jpg",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-07T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "focusrite-scarlett-2i2-4th-gen-audio-interface",
    title: "Focusrite Scarlett 2i2 4th Gen Audio Interface",
    description: "USB-C interface with two mic preamps, 192kHz/24-bit. Comes with original box, USB cable, and 3 months of Pro Tools.",
    category: "Recording",
    condition: "New",
    price: 12000,
    location: "Mumbai",
    imageUrl: "https://www.musicstores.in/img/p/4/8/8/1/4881-large_default.jpg",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-08T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "shure-sm58-microphone-stand-bundle",
    title: "Shure SM58 Microphone + Stand Bundle",
    description: "Industry-standard vocal mic with a heavy-duty boom stand. Mic is in great shape, stand folds down neatly for transport.",
    category: "Accessories",
    condition: "Good",
    price: 7500,
    location: "Delhi",
    imageUrl: "https://images.pexels.com/photos/10165653/pexels-photo-10165653.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    contactEmail: "official@gearswap.com",
    phone: "+91 98765 00000",
    createdAt: "2026-07-09T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
  {
    id: "gibson-les-paul-standard-50s",
    title: "Gibson Les Paul Standard 50s",
    description: "Heritage Cherry Sunburst with burstbucker pickups. This is a powerhouse — heavy but worth every gram. Has been professionally set up. Case not included.",
    category: "Guitars",
    condition: "Poor",
    price: 195000,
    location: "Bangalore",
    imageUrl: "https://cdn.shopaccino.com/johns-music/products/les-paul-standard-50s-cherry-sunburst-264839_l.jpg?v=730",
    contactEmail: "official@gearswap.com",
    createdAt: "2026-07-10T10:00:00.000Z",
    userId: OFFICIAL_USER_ID,
  },
];
